name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: elementary/docker:unstable
      
    steps:
    - uses: actions/checkout@v1
      with:	
        submodules: true 
    - name: Install Dependencies
      run: |
        apt update
        apt install -y gobject-introspection libgee-0.8-dev libsoup2.4-dev libgtksourceview-3.0-dev libcln-dev libgranite-dev libqalculate-dev libcurl4-openssl-dev meson valac
    - name: Build
      run: |
        meson build --prefix=/usr
        ninja -C build
