name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: elementary/docker:unstable
      
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: |
        git config --file .gitmodules --get-regexp url | while read url; do
        git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.CI_PAT }}:${{ secrets.CI_PAT }}@github.com\//")
        done
        git submodule sync
        git submodule update --init --recursive
    - name: Install Dependencies
      run: |
        apt update
        apt install -y gobject-introspection libgee-0.8-dev libsoup2.4-dev libgtksourceview-3.0-dev libcln-dev libgranite-dev libqalculate-dev meson valac
    - name: Build
      run: |
        meson build --prefix=/usr
        ninja -C build
